#!/bin/bash
if [[ -d "$HOME/sh/app/bilibili info" ]]; then
    app_type=app
    cd "$HOME/sh/app/bilibili info"
else
    app_type=dev
    cd "$HOME/sh/dev/bilibili info"
fi

if [[ $app_type == app ]]; then
    if [ -z $1 ]; then
        $HOME/Library/"Bilibili Helper"/app
    elif [ $1 = "-h" ]; then
        cat help
    elif [ $1 = "-c" ]; then
        vim $HOME/Library/"Bilibili Helper"/bv
    elif [ $1 = "-l" ]; then
        cat  $HOME/Library/"Bilibili Helper"/bv
    else
        ./app "$@"
    fi
else
    ./app "$@"
fi
