#!/bin/bash

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
export tp="$SCRIPT_DIR/tools"
export ap="$SCRIPT_DIR"

if [[ -d "$ap/app/bilibili info" ]]; then
    app_type=app
    cd "$ap/app/bilibili info"
else
    app_type=dev
    cd "$ap/dev/bilibili info"
fi

if [[ $app_type == app ]]; then
    if [ -z $1 ]; then
        $HOME/Library/"Bilibili Helper"/app
    elif [ $1 = "-h" ]; then
        cat help
    elif [ $1 = "-c" ]; then
        vim $HOME/Library/"Bilibili Helper"/bv
    elif [ $1 = "-l" ]; then
        cat  $HOME/Library/"Bilibili Helper"/bv
    else
        ./app "$@"
    fi
else
    ./app "$@"
fi
