#!/bin/sh

up_name_input=$1
found=false

for file in "./configs"/*; do  
  unset matching
  filename=$(basename "$file")
  while IFS='=' read -r key value || [[ -n "$key" ]]; do
    if [[ -n "$key" && ! "$key" =~ ^# ]]; then
        export "$key=$value"
    fi
  done < "./configs/$filename"

  IFS=',' read -ra matching <<< "$matching"

  if [[ $found == false ]]; then
    for item in "${matching[@]}"; do
      if [[ "$up_name_input" == "$item" ]]; then
        cp ./configs/$filename ./$temp/video_info
        exit;
      fi
    done
  fi

done


  

