#!/bin/sh
set -f  # 禁用路径扩展

# 读取配置文件并设置变量
while IFS='=' read -r key value; do
if [[ -n "$key" && ! "$key" =~ ^# ]]; then
    export "$key"="$value"
fi
done < config

while IFS='=' read -r key value; do
if [[ -n "$key" && ! "$key" =~ ^# ]]; then
    export "$key"="$value"
fi
done < ./$temp/video_config

IFS=',' read -ra video_name_allowed <<< "$video_name_allowed"

if [ -n "$output_path_" ]; then
    output_path=$output_path_
fi

if [[ "$medium" == "video" ]]; then
    medium_type=mp4
    load_type=ba+bv
    download_type=mp4
else
    medium_type=m4a
    load_type=ba
    download_type=webm
fi

if [[ -d "$HOME/sh/app/bilibili info" ]]; then
    bvi_type=app
else
    bvi_type=dev
fi

video_name_network=output

if [[ $1 == -d ]]; then
    url=$2
    title=$3
    cd $temp

    # video_web_info
    touch video_title.txt
    touch video_info.txt

    yt-dlp -o "input.$download_type" "$url" -f "$load_type"

    if [[ ! -e "input.$download_type" ]]; then
        exit;
    fi

    if [[ "$url" == https://www.bilibili.com/* ]]; then
        $HOME/sh/bvi "$url"
        cp $HOME/sh/$bvi_type/"bilibili info"/bv_info.txt video_info.txt
    elif [[ "$url" == https://www.youtube.com/* ]]; then
        yt-dlp -j "$url" | jq -r '
        "bv_title=" + .title,
        "bv_up=" + .uploader,
        "bv_uid=" + (.uploader_id // "N/A"),
        "bv_playback=" + (.view_count | tostring),
        "bv_likes=" + (.like_count | tostring),
        "bv_release=" + (
            .upload_date 
            | capture("(?<y>....)(?<m>..)(?<d>..)") 
            | "\(.y)-\(.m)-\(.d)T00:00:00Z"
        )
        ' > video_info.txt
    fi
    
    while IFS='=' read -r key value; do
    if [[ -n "$key" && ! "$key" =~ ^# ]]; then
        export "$key"="$value"
    fi
    done < video_info.txt

    echo "$bv_title" > video_title.txt
    
    if [[ "$medium" == "video" ]]; then
        if [[ -z "$volume" || "$volume" == "1.0" ]]; then
            ffmpeg -i input.$download_type -c:v copy -c:a aac -b:a 192k output.$medium_type
        else
            ffmpeg -i input.$download_type -c:v copy -c:a aac -b:a 192k -filter:a "volume=$volume" output.$medium_type
        fi   
    else
        if [[ -z "$volume" || "$volume" == "1.0" ]]; then     
            ffmpeg -i input.$download_type -vn -c:a copy output.$medium_type
        else  
            ffmpeg -i input.$download_type -vn -acodec aac -b:a 192k -filter:a "volume=$volume" output.$medium_type
        fi   
    fi

    if [ ! $? -eq 0 ]; then
        rm ./output.$medium_type
    fi

    if [[ ! -e "./output.$medium_type" ]]; then
        exit;
    fi

    mv ./output.$medium_type "$output_path/$bv_title.$medium_type"
    cd ../

elif [[ $1 == -u ]]; then
    url="$2"
    title="$3"
    auto_define_title_name="$3"
    
    if [[ ! -e "$url" ]]; then
        exit;
    fi
    mv "$url" ./$temp/output.m4a
    
    if [ -e "$artwork" ]; then
        ffmpeg -i ./$temp/output.m4a -map 0:a -c copy ./$temp/output_clean.m4a
        mv ./$temp/output_clean.m4a ./$temp/output.m4a
        if [ ! $? -eq 0 ]; then
            rm ./$temp/output.m4a
        fi
    fi

    if [[ ! -e "./$temp/output.m4a" ]]; then
        exit;
    fi
    
    while IFS='=' read -r key value; do
    if [[ -n "$key" && ! "$key" =~ ^# ]]; then
        export "$key"="$value"
    fi
    done < ./$temp/video_info.txt
    
    if [ -z "$title" ]; then
        if [[ ! -z "$bv_title" ]]; then
            title="$bv_title"
        else
            filename=$(basename "$url")
            title="${filename%.*}"
        fi
    fi

    ./mapper $bv_up
    
    while IFS='=' read -r key value; do
    if [[ -n "$key" && ! "$key" =~ ^# ]]; then
        export "$key"="$value"
    fi
    done < ./$temp/video_config

    if [[ -z $name ]]; then
        name="@title"
    fi
    
    IFS='@' read -ra name_parts <<< "${name:1}"

    for i in "${!name_parts[@]}"; do
        found_in_allowed=false
        name_part=${name_parts[$i]}
        echo $name_part
        for item in "${video_name_allowed[@]}"; do
            if [[ "$name_part" == $item* ]]; then
                found_in_allowed=true
                break
            fi
        done
        if [[ $found_in_allowed == "true" ]]; then
            if [[ $item == "date" ]]; then
                item_=${bv_release:0:10}
            elif [[ $item == "title" ]]; then
                item_=$title
            fi
            new_title=$new_title$item_${name_part#"$item"}
        else
            echo "this name donot exist in video_name_allowed"
            exit;
        fi 
    done

    if [[ -z $auto_define_title_name ]]; then
        auto_define_title_name=$new_title
    fi

    AtomicParsley ./$temp/output.m4a --artist "$artist" --album "$album" --composer "$composer" --title "$auto_define_title_name" --year "$year" --genre "$genre" --artwork $artwork --overWrite

    if [[ $auto_compress == true ]]; then
        mv ./$temp/output.m4a ./$temp/output_compressing.m4a
        if [[ -z $compress_param ]]; then
            compress_param=b128
        fi
        $HOME/sh/mcp $compress_param $HOME/sh/app/youtube2music/$temp/output_compressing.m4a $HOME/sh/app/youtube2music/$temp/output.m4a
        if [[ ! -e "./$temp/output.m4a" ]]; then
            exit;
        fi
    fi

    osascript -e "tell application \"Music\" to add POSIX file \"${HOME}/sh/app/youtube2music/$temp/output.m4a\""
    
elif [[ $1 == -c ]]; then
    $HOME/sh/tools/open_file_with_app config "$($HOME/sh/tools/resolve_app "$config_app")"
elif [[ $1 == -h ]]; then
    cat help
elif [[ $1 == -a ]]; then
    config_name=$2
    config_name_new=$3
    cd ./video_configs
    if [ ! -e "$config_name" ]; then
        cp ./.$template ./$config_name
    fi
    if [ ! -z "$config_name_new" ]; then
        mv ./$config_name ./$config_name_new
    else
        $HOME/sh/tools/open_file_with_app $config_name "$($HOME/sh/tools/resolve_app "$video_config_app")"
    fi 
elif [[ $1 == -l ]]; then
    ls video_configs
elif [[ $1 == -* ]]; then
    echo "option false"
else
    export output_path_=$HOME/sh/app/youtube2music/$temp
    ./app -d $1
    
    video_name=$2
    video_name_network="$(cat $temp/video_title.txt)"

    ./app -u "$HOME/sh/app/youtube2music/$temp/$video_name_network.$medium_type" $video_name
fi

set +f
