#!/bin/bash

[[ $platform == "youtube" ]] && defalut_matching_sub=@url:watch || defalut_matching_sub=@url:video

for file in "$local_path"/video_configs/*; do  
  unset matching && unset matching_sub
  filename=$(basename "$file")
  source "$tp"/e2s "$local_path"/video_configs/$filename
  IFS=',' read -ra matching <<< "$matching"
  [[ -z $matching_sub ]] && matching_sub=$defalut_matching_sub
  matching_sub_k="${matching_sub%%:*}" && matching_sub_v="${matching_sub#*:}"
  [[ $matching_sub_k != @url ]] && echo "using false key in matching_sub" && exit; 

  for item in "${matching[@]}"; do
    if [[ "$bv_up" == $item && "$url" == *$matching_sub_v* ]]; then
        cp "$local_path"/video_configs/$filename ./video_config
        if [[ $name == *@custom* ]]; then
            filename=$(basename "$local_path"/customs/$filename*) && ext="${filename##*.}"
            cp "$local_path"/customs/$filename custom.$ext
            exe_app=$(eval "echo \$exe_$ext")
            echo "$exe_app "./custom.$ext" \"$bv_title\"" > custom_command.sh
            chmod +x custom_command.sh
        fi
        exit;
    fi
  done
done
