#!/bin/sh

compress_mode=$1 && compress_para="$2"
o_path="$3" && d_path="$4"
file_name="$(basename "$o_path")"
media_type=".${file_name##*.}"
media_type=$(echo "$media_type" | tr '[:upper:]' '[:lower:]')

if [ -z "$d_path" ]; then
    d_path="$(dirname "$o_path")/${file_name%.*}${compress_mode}$compress_para$media_type"
elif [ -d "$d_path" ]; then
    if [[ $compress_mode == "-preset" ]]; then
        d_path="$d_path/${file_name%.*}${compress_mode}$media_type"
    else
        d_path="$d_path/${file_name%.*}${compress_mode}$compress_para$media_type"
    fi
fi

if [[ $media_type == '.mp4' || $media_type == '.mov' ]]; then
    [[ $compress_mode == '-preset' ]] && ./libexec/video_info "$compress_para" || ./libexec/video_info "$o_path"
    source $tp/e2s $temp/media_info
    ./libexec/media_time "$o_path" && source $tp/e2s $temp/media_time && media_time_old=$md
    [[ $auto_encoder_accelerate == "true" ]] && h264_encoder=$h264_encoder_acc || h264_encoder=$h264_encoder_universal
    if [[ $compress_mode == '-c' ]]; then
        h264_encoder=$h264_encoder_universal
        ffmpeg -i "$o_path" \
        -vcodec $h264_encoder -crf "$compress_para" \
        -acodec aac -b:a $ab \
        -preset slow \
        "./$temp/$file_name"
    elif [[ $compress_mode == '-b' ]]; then
        if (( $(echo "$compress_para >= 0.01 && $compress_para < 1" | bc -l) )); then
            vb=${vb%k} && vb=$(echo "$vb * $compress_para" | bc) && vb="${vb}k"
        elif (( $(echo "$compress_para >= 1 && $compress_para <= 10" | bc -l) )); then
            vb=$(echo "$compress_para * 1000" | bc) && vb="${vb}k"
        else
            echo "compress_para($compress_para) false, it must from 0.01 to 10" && exit
        fi
        ffmpeg -i "$o_path" \
        -c:v $h264_encoder -b:v $vb \
        -c:a aac -b:a $ab \
        -preset slow "./$temp/$file_name"
    elif [[ $compress_mode == '-preset' ]]; then
        ffmpeg -i "$o_path" \
        -vf "scale=${wr}:${hr}:flags=$video_scale_flags" \
        -c:v $h264_encoder -b:v $vb \
        -c:a aac -b:a $ab \
        -preset slow "./$temp/$file_name"
    else
        echo "Unsupported compress mode: $compress_mode" && exit
    fi
    ./libexec/media_time "./$temp/$file_name" && source $tp/e2s $temp/media_time && media_time_new=$md
elif  [[ $media_type == '.m4a' || $media_type == '.mp3' ]]; then
    if [[ $compress_mode == '-b' ]]; then
        ffmpeg -i "$o_path" -vn -c:a aac -b:a ${compress_para}k -f ipod "./$temp/$file_name"
    else
        echo "Unsupported compress mode: $compress_mode" && exit
    fi
elif  [[ $media_type == '.gif' ]]; then
    if [[ $compress_mode == '-r' ]]; then
        # both wide and len exceed $protect_dim_gif, this option will
        # both wide and len exceed $forbid_dim_gif, and wide or len exceed $protect_dim_gif, this option will
        # you can change $protect_dim_gif and $forbid_dim_gif in config

        wide_and_len=$(identify -format "%w %h" "$o_path[0]")
        wide=$(echo "$wide_and_len" | cut -d' ' -f1)
        len=$(echo "$wide_and_len" | cut -d' ' -f2)
        
        if [[ $protect_dim_gif -lt $wide && $protect_dim_gif -lt $len ]]; then
            wide=$(echo "$wide * $compress_para" | bc -l | xargs printf "%.0f")
            len=$(echo "$len * $compress_para" | bc -l | xargs printf "%.0f")
            gifsicle -O3 --colors 256 --resize ${wide}x${len} "$o_path" -o "./$temp/$file_name"
        else
            if [[ $forbid_dim_gif -lt $wide && $forbid_dim_gif -lt $len ]]; then
                if [[ $protect_dim_gif -lt $wide || $protect_dim_gif -lt $len ]]; then
                    wide=$(echo "$wide * $compress_para" | bc -l | xargs printf "%.0f")
                    len=$(echo "$len * $compress_para" | bc -l | xargs printf "%.0f")
                    gifsicle -O3 --colors 256 --resize ${wide}x${len} "$o_path" -o "./$temp/$file_name"
                else
                    file_name_without_ext="${file_name%.*}"
                    file_name=${file_name_without_ext}${compress_mode}${compress_para}_failed_{protect_dim_gif}${media_type}
                    d_path="$(dirname "$d_path")/${file_name}"
                    cp "$o_path" "./$temp/$file_name"
                fi 
            else
                file_name_without_ext="${file_name%.*}"
                file_name=${file_name_without_ext}${compress_mode}${compress_para}_failed_{forbid_dim_gif}${media_type}
                d_path="$(dirname "$d_path")/${file_name}"
                cp "$o_path" "./$temp/$file_name"
            fi
        fi
    elif [[ $compress_mode == '-f' ]]; then
        echo "don't use this now"
        exit
        frame_count=$(gifsicle -I "$o_path" | grep "image #" | wc -l)
        duration=$(ffprobe -v error -show_entries format=duration -of default=noprint_wrappers=1:nokey=1 "$o_path")
        avg_delay=$(echo "$duration / $frame_count" | bc -l)
        echo $frame_count $duration $avg_delay

        mod_base=10
        fps_compress_per=$(echo "10 * $compress_para" | bc -l | xargs printf "%.0f")
       
        # 计算要保留的帧位置(加权居中分布)
        picks=()
        for ((i=0; i<fps_compress_per; i++)); do
            index=$(( (i * mod_base + fps_compress_per / 2) / fps_compress_per )) 
            echo $index && picks+=("$index")
        done
        
        # 构建 select 表达式：eq(mod(n\,10)\,x1)+eq(mod(n\,10)\,x2)+...
        expr=""
        for pick in "${picks[@]}"; do
            [[ -n "$expr" ]] && expr+="+"
            expr+="eq(mod(n\\,$mod_base)\,$pick)"
        done
        ffmpeg -i "$o_path" -vf "select='${expr}',setpts=N/FRAME_RATE/TB" -vsync 0 "./$temp/_${file_name}"
        new_delay=$(echo "$avg_delay * 100 / $compress_para" | bc -l)
        gifsicle  --unoptimize "./$temp/_${file_name}" --delay=$(printf "%.0f" "$new_delay") -o "./$temp/$file_name"
    else
        echo "Unsupported compress mode: $compress_mode" && exit
    fi
elif  [[ $media_type == '.heic' ]]; then
    if [[ $compress_mode == '-q' ]]; then
        file_name="${file_name%.*}".jpg
        d_path="${d_path%.*}".jpg
        ffmpeg -i "$o_path" -frames:v 1 -qscale:v $compress_para 
        convert "$o_path" -quality $compress_para "./$temp/$file_name"
    elif [[ $compress_mode == '-j' ]]; then
        file_name="${file_name%.*}".jpg
        d_path="${d_path%.*}".jpg
        sips -s format jpeg -s formatOptions $compress_para "$o_path" --out "./$temp/$file_name"
    else
        echo "Unsupported compress mode: $compress_mode" && exit
    fi
elif  [[ $media_type == '.png' || $media_type == '.jpg' || $media_type == '.jpeg' ]]; then
    if [[ $compress_mode == '-j' ]]; then
        file_name="${file_name%.*}".jpg && d_path="${d_path%.*}".jpg
        sips -s format jpeg -s formatOptions $compress_para "$o_path" --out "./$temp/$file_name"
    else
        echo "Unsupported compress mode: $compress_mode" && exit
    fi
else
    echo "Unsupported file type: ${file_name##*.}" >&2 && exit
fi

exiftool -TagsFromFile "$o_path" -all:all -overwrite_original "./$temp/$file_name"
if [[ ! -z $media_time_old ]]; then
    [[ $media_time_old != $media_time_new ]] && exit
fi
mv "./$temp/$file_name" "$d_path"
