#!/bin/sh
set -f  # 禁用路径扩展
cd ~/sh/app/youtube2music

while IFS='=' read -r key value; do
  if [[ -n "$key" && ! "$key" =~ ^# ]]; then
    export "$key"="$value"
  fi
done < config

temp_local="temp"

while [[ -d "$temp_local" ]]; do
  temp_local="temp"${i}
  ((i++))
done

export temp=$temp_local
mkdir $temp_local

if [[ $1 == "-version" ]]; then
    echo $version
elif [[ $1 == "-readme" ]]; then
    $HOME/sh/tools/open_file README.md $readme_app
elif [[ $1 == -p ]]; then
    cp ./resources/video_configs/$2 ./$temp_local/video_config
    ./app "${@:3}"
else
    cp ./resources/video_configs/$defalut ./$temp_local/video_config
    ./app $@
fi

rm -r $temp_local

set +f
