#!/bin/bash

resolve_app() {

    resolve_app="$1"
    
    if [[ $resolve_app == "vscode" ]]; then
        resolve_app="Visual Studio Code"
    elif [[ $resolve_app == "txt" ]]; then
        resolve_app="TextEdit"
    elif [[ $resolve_app == "terminal" ]]; then
        resolve_app="vim"
    fi

}

resolve_app "$1"
echo "$resolve_app"
