#!/bin/bash

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
export tp="$SCRIPT_DIR/tools"
export ap="$SCRIPT_DIR"

[[ -e "$1" ]] && abs_path="$(realpath "$1")"
[[ -z $1 ]] && abs_path=$PWD

cd "$SCRIPT_DIR"/app/open_pro
source "$tp"/e2s config && source "$tp"/e2s system_config

if [[ $1 == -version ]]; then
    echo $version
elif [[ $1 == -h ]]; then
    cat help
elif [[ $1 == -c ]]; then
    $ap/op config
elif [[ $1 == -* ]]; then
    ./bin/cmd "$@"
else
    if [[ -z $abs_path ]]; then
        abs_path=$HOME/$1
        touch $1 && ./app $abs_path
    else
        [[ ! -e $abs_path ]] && touch $abs_path
        ./app "$abs_path"  "${@:2}"
    fi
fi
